export enum RpcErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',

  USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
  
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}