export enum RpcErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',

  USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
  USERNAME_CHANGE_TIMEOUT = 'USERNAME_CHANGE_TIMEOUT',
  USERNAME_SAME_AS_CURRENT = 'USERNAME_SAME_AS_CURRENT',

  USER_LINK_LIMIT_REACHED = 'USER_LINK_LIMIT_REACHED',
  USER_LINK_URL_TYPE_MISMATCH = 'USER_LINK_URL_TYPE_MISMATCH',
  USER_LINK_NOT_FOUND = 'USER_LINK_NOT_FOUND',
  
  
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}