export const AUTH_KAFKA_CLIENT = 'AUTH_KAFKA_CLIENT';

export const REFERENCE_KAFKA_CLIENT = 'REFERENCE_KAFKA_CLIENT';

export const PROFILE_KAFKA_CLIENT = 'PROFILE_KAFKA_CLIENT';

export const MEDIA_KAFKA_CLIENT = 'MEDIA_KAFKA_CLIENT';