export enum RpcErrorCode {
  // AUTH
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_EMAIL_VERIFICATION_TOKEN = 'INVALID_EMAIL_VERIFICATION_TOKEN',
  INVALID_PASSWORD_RESET_TOKEN = 'INVALID_PASSWORD_RESET_TOKEN',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_DELETED = 'USER_DELETED',

  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  EMAIL_VERIFICATION_RESEND_TOO_SOON = 'EMAIL_VERIFICATION_RESEND_TOO_SOON',

  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',

  INVALID_ACCOUNT_RESTORE_TOKEN = 'INVALID_ACCOUNT_RESTORE_TOKEN',
  ACCOUNT_RESTORE_REQUEST_TOO_SOON = 'ACCOUNT_RESTORE_REQUEST_TOO_SOON',
  
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',

  // PROFILE
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',

  // REFERENCE
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}